language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
addons:
  apt:
    update: true
install:
  - pip install pip==20.2.0
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  - ./analyse-code.sh
after_success:
  - coveralls
notifications:
  email: false
