"""Initial

Revision ID: 384f0371e083
Revises: 12dbd9dca2c4
Create Date: 2022-01-16 20:37:34.844375

"""
# revision identifiers, used by Alembic.
revision = "384f0371e083"
down_revision = "12dbd9dca2c4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
